baseurl: "/"
languageCode: "en-us"
defaultContentLanguage: "en"
title: "prateek grover"
theme: "hugo-prose"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"
pagination.pagerSize: 20

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]


# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: work
      url: "/work"
      weight: 1
    # - name: research
    #   url: "/research"
    #   weight: 2
    # - name: projects
    #   url: "/projects"
    #   weight: 3
    # - name: media
    #   url: "/media"
    #   weight: 4
    # - name: misc :)
    #   url: "/misc"
    #   weight: 5
  footer:
    - name: Categories
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: Tags
      url: "/tags/"
      weight: 3
      pre: "optional"
    - name: Back to top
      url: "#"

params:
  homePosts: 0
  mainSections: 
  editLink: "https://github.com/yihui/hugo-prose/edit/master/exampleSite/content/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    A website built through Hugo and blogdown with the hugo-prose theme.
  footer: >
    &copy; Prateek Grover 2025
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT. The full source is available at
    https://github.com/yihui/hugo-prose.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
